### PR TITLE
Delete node_modules patch + Update deps

### PR DESCRIPTION
**Pull request by bcomnes**
Seems to be launching all the browsers still.  PhantomJs is still broken, but also depreciated.

### CODE REVIEW

**Comment by jgravois** [comment]
hi there! 👋  any chance of this PR (or #49) landing?

either way, bumping to `"minimist": "^1.2.5"` would resolve this package's sole reported security vulnerability.

**Comment by bcomnes** [comment]
Yeah, I can take a look

**Comment by bcomnes** [comment]
@jgravois ok im going to do a 3.0.0 beta release.  Can you test it and let me know how it goes?

**Comment by bcomnes** [comment]
`npm i browser-launcher@beta`

If you can validate that for me I will land and release a 3.0.0

**Comment by jgravois** [comment]
thanks so much!🥇 

i created a dummy project, pulled down your beta tag and confirmed:
1. the snippet in the README still launches a browser window
2. `0` security vulnerabilities remain.

**Comment by bcomnes** [comment]
Cool, I'll get a 3.0.0 proper out

**Comment by bcomnes** [comment]
v3.0.0

**Pull request merged**
