### PR TITLE
Fix browsers detection for macOS

### PR DESCRIPTION
**Pull request by fanatid**
Replacement of https://github.com/substack/browser-launcher/pull/51

Fix:
- errors handles
- plist usage

### CODE REVIEW

**Comment by bcomnes** [comment]
Can you explain the issue briefly? Otherwise its probably good to go.  I just want some context before I merge.

**Comment by fanatid** [comment]
Issue with new `plist` version: now `plist.parse` is sync instead of `plist.parseFile` which was async. Usage examples on npm: https://www.npmjs.com/package/plist.

The second issue with unhandled errors which produce errors like (real example):
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
```

If you want I can split this PR to two: plist and callbacks.

**Comment by bcomnes** [comment]
No, I dont need 2 prs.  Just not using this much lately, so unfamiliar with the faults. Changes look fine, if you can help monitor the release for newly introduced issues, I can run releases for you.

**Review by bcomnes — APPROVED** [review]

**Comment by bcomnes** [comment]
browser-launcher (3.0.1)

**Comment by fanatid** [comment]
Thanks a lot!

**Pull request merged**
